### ISSUE TITLE
frontend payment stuff + custom domain

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#198]
---
title: "pogo customerportal"
date: "2020-12-09"
---

| taak                               | status                            | check               | conditions                         |
|------------------------------------|-----------------------------------|---------------------|------------------------------------|
| user member                        | no / unconfirmed / active         | board_api           |                                    |
| site published                     | never / unknown / last date       | config              | publishable: member & site claimed |
| site publication                   | never / pending / finished        | pogo_with_me /local | publishable: member & site claimed |
| site changes                       | up to date / unpublished changes  | local               | publishable: member & site claimed |
| site xxx.pogosite reachable        | yes / no                          | pogo_with_me        | publishable: member & site claimed |
| site basic subscription            | none / pending / active / expired | pay_api             | subscrible: member                 |
| site custom domain reachable       | yes / no                          | pogo_with_me        | active_subscription                |
| site https custom domain reachable | yes / no                          | pogo_with_me        | active_subscription                |

## POGOPAY

* [x] include gitlab
  * [x] sloop client eruit
* [x] templating and branding
* [x] favicon
* [x] start personal message
* [x] succeed personal message
* [x] find user by custom_attribute
* [x] customerportal
* [x] bij boarden ook project owner toevoegen
* [x] add membership to project and user
* [x] webhook upgrade succeed
  * [x] delete pending
  * [x] delete vars
  * [x] add start en end period
* [x] als mandje niet klop foutmelding
* [x] beveiliging: controleren of gebruiker wel toegang heeft tot customerportal (sshkey?)
  * [x] genereer fingerprint met embgit
  * [x] verwijder pub key na uploaden poppygo
  * [x] pogopay customerportal: valideer gebruiker via fingerprint
  * [x] pogopay upgrade: valideer gebruiker via fingerprint
  * [x] pogoboard claim domain: valideer gebruiker via fingerprint
* [x] pogocli: show all relevant details for user
  * [x] owned projects (sites) with custom_attrubutes
  * [x] custom attributes
  * [x] amount of projects
* [x] show all relevant info for projects
  * [x] members
* [x] met terugwerkende kracht ook project owner bij ander klanten toevoegen
* [x] pogocli: make user confirmed
* [x] pogocli: make project owned by user
* [x] poll for unconfirmed member
* [x] resend confirmation mail endpoint
* [x] cancel pending subscr process
* [x] why is success and webhook seperated?
  * [x] move all saving from success to webhook
* [x] poll in app upgrade succeed
  * [x] bij request pending status wegschrijven
  * [x] bij openen controleren of pending status aanwezig is en gaan pollen
  * [?] poll checked bij board/sinatra of project gekoppeld is in gebruiker
  * [x] bij request polling starten
  * [x] ook sessionId wegschrijven in upgradePending
    * [x] remove backend api code
* [x] quietly ignore connection refused (test with all servers down)
* [x] na claimen domein pollen
* [x] link domain functionality
  * [x] cli query
  * [x] board endpoint domain add
  * [x] handler
  * [x] list domains
  * [x] get custom domain remote only one
    * [x] remove defaultSite functionality in pogoConf
  * [x] board endpoint domain delete/update
* [x] deployment
* [x] do not allow to publish if not owner
* [x] alleen mogelijk om te upgraden als email confirmed, doe dit op de website niet in de app
* [x] create project with some files
  * [x] gitlab.cr repo create file
  * files
    * [x] .gitlab-ci
    * [x] static index
    * [x] pogo with me
* [x] unsubscribe functionality
* [ ] monitoring
* [ ] transacties dumpen in issues
* [x] documenteren DNS records poppygo
* [ ] check custom domain dns ok pogowithme reachable
  * [x] simple check
  * [ ] time out check

## Volledige test
- maak nieuwe gebruiker
- maak nieuw domein
- publiceer domein
- bevestig email
- upgrade domein

## Stripe vragen
* [ ] renew substription: hoe werkt dit

## Samples test in ruby

* [x] https://github.com/stripe-samples/checkout-single-subscription

## Gitlab Shard

* [x] gitlab.cr indienen pull request custom_attributes
  * [x] project and groups
  * [x] delete probleem oplossen
* [x] gitlab.cr keybyfingerprint pr indienen
* [x] additional_props in crystal shard (project)
    * [x] list c_a
    * [x] single c_a
    * [x] put c_a
    * [x] delete c_a
* [x] meer deletes migraties toevoegen
* [x] singles for custom attributes
* [x] fix halite 0.10.7 endpoint error
* [x] fix comments on PR

## Gitlab GEM

* [x] additional_props in gitlab gem (user)
    * [x] list c_a
    * [x] single c_a
    * [x] put c_a
    * [x] delete c_a
* [x] additional_props in gitlab gem (project)
    * [x] list c_a
    * [x] single c_a
    * [x] put c_a
    * [x] delete c_a
* [x] gitlab-gem indienen pull request
  * [x] ook groups?
  * [x] fout in spec
