### ISSUE TITLE
invite member

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#275]
- [x] invite member dialog by email
- [x] PogoBoard
- [x] download as member
- [ ] display membership in repos
- [ ] remove member
