### ISSUE TITLE
auto build scripts for macOS and Windows and Linux

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#279]
- [x] move repository-code with history to GitHub private
  - [x] clone git repo to mipmip
  - [x] clone git repo to swanenberg
  - [x] new origin on mipmip devs copies
  - [x] new origin on swanenberg devs copies

```git remote set-url origin git@github.com:swanenberg/poppygo-electron-app.git```

```git remote set-url origin git@github.com:mipmip/poppygo-electron-app.git```

  - [x] rename master to main (history neutral) pim
  - [x] rename master to main (history neutral) brecht

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

  - [x] cleanup old branches remote
  - [x] cleanup local

```git branch | grep -v 'main' | xargs git branch -D```

- [x] cleanup buildscripts
- [x] setup build scripts on GitHub
  - [x] Windows 10 en 11
  - [x] Mac plus Notarization and code signing
  - [x] Linux
  - [x] special rules for automatic builds
  - [x] release rule
- [x] add documentation to company-book
  - [x] new PR strategy -> use user forks

# POGOFORK
- [x] name auto to version
- [x] upload script
- [x] deploy quiqr.app
- [x] build linux version
- [x] build on github
  - [x] linux
    - [x] publish as snapcraft
      - [x] geen fout niet zichtbaar
    - [x] publish to s3
      - [x] publish as appimage
      - [x] publish as .deb
      - [x] rpm
  - [x] windows
    - [x] publish to s3
  - [x] mac
    - [x] code sign
    - [x] notarize mac

### release script with github actions
- [x] altijd vanuit tag
- [x] show current version:ask for new version, and set in package.json
- [x] warn check CHANGELOG.md
- [x] create and push tag with new version
