### ISSUE TITLE
multitple assetmanager improvements

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#289]
- [x] show checker background for transparent images
- [x] preview all filetypes
- [x] show GIFs
- [x] show SVGs
- [x] remove thumbnail too when file is deleted
