### ISSUE TITLE
Keyboard navigation throught app

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#291]
### Main application
- [ ] shortcut to focus left navigation
- [ ] shortcut to focus dashboard
- [ ] shortcut to toggle preview
- [ ] shortcut to open current doc in browser
- [ ] shortcut to open current doc in editor

### Dialogs

- [ ] <kbd>escape</kbd> to cancel and close
  - [ ] <kbd>tab</kbd>

- [ ] arrow keys through navigation left
  - [ ] <kbd>up</kbd> and <kbd>down</kbd>
  - [ ] <kbd>enter<kbd> go into selected item
- [ ] single and collection item form
  - [x] <kbd>tab</kbd> next input
    - [ ] skip context help
  - [ ] <kbd>Meta+S</kbd> save form
  - [ ] <kbd>enter</kbd> to go into accordion subform
  - [x] <kbd>space</kbd> to change switch
