### ISSUE TITLE
Git remote site versions

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#296]
## UX
- [x] display remote site versions
- [x] push try merge
- [x] push overwrite
- [x] sync or push/pull buttons

## Implementation
- [x] display remote site versions
- [x] checkout special version

**Comment by mipmip** [comment]
![Image](https://user-images.githubusercontent.com/658612/232870670-ad6374f5-285b-48de-aed8-3a8ee41f266b.png)
