### ISSUE TITLE
Hugo Draft Mode

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#303]
- [ ] visualize drafts in application
- [ ] visualize drafts in list
- [x] show hide drafts
- [x] don't publish drafts
