### ISSUE TITLE
NixOS Issues

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#305]
## Divers
- [x] progress dialog houdt programma vast (new from directory als voorbeeld)
- [x] preview in browser werkt
- [x] icon werkt niet
- [x] nix forum vraag over shell
- [x] link naar firefox werkt niet
- [x] open in finder werkt niet

### Working AppImage in NixOS

- [x] hugo
- [x] browser
- [x] embgit

## Eerder problem firefox

```
/nix/store/wv35g5lff84rray15zlzarcqi9fxzz84-bash-4.4-p23/bin/sh: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/kp772v3mgq77ssjddys61xk7ajfvvphj-libX11-1.7.2/lib/libX11.so.6)
/nix/store/wv35g5lff84rray15zlzarcqi9fxzz84-bash-4.4-p23/bin/sh: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/zyrvkz2yp021x6bxl31856c34rrggw5q-libXau-1.0.9/lib/libXau.so.6)
```
