### ISSUE TITLE
electron 9 upgrade

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#322]
- [x] images can't be added anymore
- [x] image thumbs are very big
- [x] log window not working
- [x] all renderer remote post class fail
  - [x] claimdomain
  - [x] DisconnectDomainDialog.js
  - [x] register
  - [x] EditPlanDialog.js
  - [x] ConnectDomainDialog.js
  - [x] HomeSimple (handleResendConfirmationMail)
