### ISSUE TITLE
publish to github

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#350]
- [x] new design home screen
  - [x] add github publish target
  - [x] remove github publish target
- [x] auto generate key
- [x] proto type publish to github in code
- [x] design publish to github
- [x] test in combination with quiqr cloud publish
