### ISSUE TITLE
publish to quiqr.cloud on invitation

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#351]
- [ ] send invitation request after entering mail
- [ ] approval method
- [ ] documentation
- [ ] port all existing func
- [ ] test all func
