### ISSUE TITLE
Site Library UX Quiqr-UX v2.svg

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#354]
- [x] [site]/quiqr/etalage (local)
   - [x] no screenshot available
   - [x] screenshot creator
   - [x] favicon
- [x] On My computer with Tags
- [x] remember menu state with /sites/last
- [x] matchRole in menu
