### ISSUE TITLE
implement Application Roles

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#362]
- [x] implement in experimental
- [ ] list of useful places
  - [x] content dashboard/menu
  - [x] toolbar -> tools
- [x] move to real location in menu
- [ ] available in preferences
- [ ] Documentation
