### ISSUE TITLE
site library new

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#376]
- [x] from hugo theme
  - [x] embgit task
  - [x] show meta info
  - [x] choose hugo version
  - [x] extended version yes/no
  - [x] do create
- [x] from hugo dir
  - [x] choose hugo version
  - [x] extended version yes/no
- [x] refactor import/new
  - [x] samenvoegen met import 
- [x] from scratch
  - [x] choose hugo version
  - [x] extended version yes/no 
  - [x] configFormat not working
