### ISSUE TITLE
new quiqr-data dir structure

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#378]
all site data inside the directory.

- [x] default dir: Quiqr
- [x] remove root/config.json with theme
- [x] move theme setting to prefs

## Use new location for config.json
- [x] rewrite in src-main/app-prefs-state/configuration-data-provider.js
- [x] use new location update
  - [x] tags
  - [x] rename
- [x] new location at
  - [x] create
  - [x] copy
  - [x] delete
  - [x] import

![Screenshot from 2022-06-08 14-44-58](https://user-images.githubusercontent.com/658612/172619634-f1b5b5e1-7ccf-4b75-a0f2-40702a0810e0.png)
