### ISSUE TITLE
sync from remote

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#423]
- [x] sync from remote with folderEndPoint
- [x] sync from remote with git endpoint
- [x] show snack status when sync to succes/fail
- [x] only show sync from buttons when source files are available on remote
- [x] ask to automatically setup sync target when importing site from folder/git
- [x] show snack status when sync from succes/fail
