### ISSUE TITLE
make config.json source path agnostic

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#452]
## Config.json
- [x] separate config and state file
- [x] replace source/path with relative path in config.json
  - [x] siteconf openfile actions
  - [x] src-main stuff
- [ ] remove sitekey from config.json (always use foldername as site key)
