### ISSUE TITLE
scaffold tool

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#492]
read file and auto create model

- [x] implement single
- [x] implement collection
- [x] auto add to menu
- [ ] test pullOuterRootKey
- [ ] enable menu item only when site is loaded
- [x] move out of experimental
- [ ] documentation
- [ ] run at new from theme or from scratch
- [ ] create more readable names and keys
