### ISSUE TITLE
run extra http server with SEO analyser

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#499]
- [ ] make UI of previewer website for browser with sidebar
- [x] setup react + mui for sidebar
- [x] tab based menu sidebar (panels)
- [ ] run extra hugo or inject page

## panels

- [x] social preview panel
- [ ] plain html tags recommendations
- [ ] keywords seo analysis (density)
- [x] title stuff
- [ ] headline structure
